name: Build and deploy Docker app to Azure Web Apps

on:
  push:
    branches:
      - main
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: "arehman-fastapi-demo"
      IMAGE_NAME: "${{ secrets.REGISTRY_LOGIN_SERVER }}/fastapi-demo:${{ github.sha }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Azure CR Authentication'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push image to ACR'
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}

      - name: Deploy ACR Image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}
