name: Terraform CI/CD

on:
  push:
    branches:
      - infra
    # paths:
    # - 'terraform/**'

jobs:
  terraform_provisioning:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./terraform/test
    env:
      ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
  
        - name: Terraform Init
          id: init 
          run: |
            terraform init

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Plan
          id: plan
          run: |
            terraform plan
    
        - name: Terraform Apply
          id: apply
          run: |
            terraform apply -auto-approve
